In [2]:
import numpy as np
import pandas as pd

In [8]:
df = pd.read_csv('./dataset/data_for_ohe.csv')

In [9]:
df.head()

   gender race/ethnicity         lunch  math score  reading score
0  female        group B      standard          72             72
1  female        group C      standard          69             90
2  female        group B      standard          90             95
3    male        group A  free/reduced          47             57
4    male        group C      standard          76             78

In [11]:
print(df['gender'].unique())
print(df['lunch'].unique())
print(df['race/ethnicity'].unique())

['female' 'male']
['standard' 'free/reduced']
['group B' 'group C' 'group A' 'group D' 'group E']

In [53]:
temp = pd.get_dummies(df,columns=['gender','race/ethnicity','lunch'],dtype=np.int32)

In [54]:
temp.sample(5)

,math score,reading score,gender_female,gender_male,race/ethnicity_group A,race/ethnicity_group B,race/ethnicity_group C,race/ethnicity_group D,race/ethnicity_group E,lunch_free/reduced,lunch_standard
613,65,77,1,0,0,0,1,0,0,0,1
651,68,80,1,0,1,0,0,0,0,0,1
952,74,74,1,0,0,0,0,0,1,1,0
552,40,48,1,0,0,1,0,0,0,0,1
127,65,77,0,1,0,0,0,1,0,0,1

In [55]:
temp.shape

(1000, 11)

In [ ]:
temp.sha

In [49]:
newTemp = pd.get_dummies(df,columns=['gender','race/ethnicity','lunch'],dtype=np.int32,drop_first=True)

In [50]:
newTemp.sample(5)

,math score,reading score,gender_male,race/ethnicity_group B,race/ethnicity_group C,race/ethnicity_group D,race/ethnicity_group E,lunch_standard
196,59,69,1,0,1,0,0,0
977,62,65,1,0,1,0,0,1
974,54,63,0,0,0,0,0,1
881,71,70,0,0,0,0,1,1
280,53,52,1,0,0,1,0,1

In [51]:
newTemp.shape

(1000, 8)

## One Hot Encoding Using sklearn

In [60]:
df.head()

   gender race/ethnicity         lunch  math score  reading score
0  female        group B      standard          72             72
1  female        group C      standard          69             90
2  female        group B      standard          90             95
3    male        group A  free/reduced          47             57
4    male        group C      standard          76             78

In [59]:
! pip install scikit-learn

Requirement already satisfied: scikit-learn in c:\users\prath\appdata\local\programs\python\python313\lib\site-packages (1.7.1)
Requirement already satisfied: numpy>=1.22.0 in c:\users\prath\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn) (2.3.1)
Requirement already satisfied: scipy>=1.8.0 in c:\users\prath\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn) (1.16.1)
Requirement already satisfied: joblib>=1.2.0 in c:\users\prath\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn) (1.5.1)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\prath\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn) (3.6.0)

In [81]:
from sklearn.model_selection import train_test_split

x = df.iloc[:,0:4] # independent 
y = df.iloc[:,-1] # dependent

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=2)

In [82]:
x_train # 80% DATA

     gender race/ethnicity         lunch  math score
175  female        group C      standard          81
818  female        group B  free/reduced          60
677  female        group C      standard          70
952  female        group E  free/reduced          74
200  female        group C      standard          67
..      ...            ...           ...         ...
534    male        group B      standard          73
584  female        group D      standard          69
493  female        group C      standard          81
527  female        group C  free/reduced          36
168  female        group B      standard          68

[800 rows x 4 columns]

In [83]:
from sklearn.preprocessing import OneHotEncoder

In [84]:
ohe = OneHotEncoder()

In [85]:
ohe.fit(x_train[['gender','race/ethnicity','lunch']])

OneHotEncoder()

In [ ]:
new_x_train = ohe.transform(x_train[['gender','race/ethnicity','lunch']])
new_x_test = ohe.transform(x_test[['gender','race/ethnicity','lunch']])

In [87]:
new_x_train

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 2400 stored elements and shape (800, 9)>

In [88]:
new_x_test

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 2400 stored elements and shape (800, 9)>