In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv('./Data/Housing.csv')

In [3]:
data.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished

Q1.  Write  a  program  to  find  the  average  price  of  houses  grouped  by  the  number  of  bedrooms.
Display the result in descending order of average price.

In [5]:
data.groupby('bedrooms')['price'].mean().sort_values(ascending=False)

bedrooms
5    5.819800e+06
4    5.729758e+06
3    4.954598e+06
6    4.791500e+06
2    3.632022e+06
1    2.712500e+06
Name: price, dtype: float64

Q2. Create a program to calculate the total area of houses grouped by stories. Display only the top
2 with the largest total area.

In [6]:
data.groupby('stories')['area'].sum().sort_values().tail(2)

stories
2    1132153
1    1200790
Name: area, dtype: int64

Q3.  Determine  the  maximum  price  of  houses  based  on  whether  they  have  hotwaterheating  or  not.
Also display the data of both rows

In [7]:
data.groupby('hotwaterheating')['price'].max()

hotwaterheating
no     13300000
yes     9681000
Name: price, dtype: int64

Q.4 Add a column named PricePerSqFt to calculate the price per square foot for each house. Group
the dataset by the number of floors and find the average PricePerSqFt for each group.

In [8]:
data['PricePerSqFt'] = data['price']//data['area']

In [14]:
data.groupby('stories')['PricePerSqFt'].mean()

stories
1     850.057269
2    1079.605042
3    1154.615385
4    1126.512195
Name: PricePerSqFt, dtype: float64

In [9]:
data.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus,PricePerSqFt
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished,1792
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished,1367
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished,1229
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished,1628
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished,1537

Q5.  Group  the  data  by  parking  and  count  the  total  number  of  houses  in  each  number  of  parking.
Also sort in ascending order.

In [10]:
data.groupby("parking").count()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,prefarea,furnishingstatus,PricePerSqFt
parking,,,,,,,,,,,,,
0,299,299,299,299,299,299,299,299,299,299,299,299,299
1,126,126,126,126,126,126,126,126,126,126,126,126,126
2,108,108,108,108,108,108,108,108,108,108,108,108,108
3,12,12,12,12,12,12,12,12,12,12,12,12,12

Q6.  Write  a  program  to  group  houses  based  on  the  number  of  bathrooms  and  find  the  minimum,
maximum, and average area (square feet) for each bathroom group

In [ ]:
data.groupby('bathrooms')['area'].max()

bathrooms
1    15600
2    12090
3    16200
4     8960
Name: area, dtype: int64

In [ ]:
data.groupby('bathrooms')['area'].mean()

bathrooms
1    4920.892768
2    5699.526316
3    6677.000000
4    8960.000000
Name: area, dtype: float64

In [13]:
data.groupby('bathrooms')['area'].min()

bathrooms
1    1650
2    1950
3    2610
4    8960
Name: area, dtype: int64

Q.7 Perform  all  the  attributes  and  methods  of  pandas  groupby  object  on  this  dataset  which  are
discussed in class and analyse the data.

In [15]:
data.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus,PricePerSqFt
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished,1792
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished,1367
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished,1229
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished,1628
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished,1537

In [16]:
mainroad = data.groupby('mainroad')

In [17]:
mainroad.groups

{'no': [143, 157, 169, 180, 182, 189, 197, 201, 263, 271, 282, 290, 292, 293, 294, 295, 316, 324, 326, 327, 328, 348, 356, 357, 364, 368, 372, 377, 384, 390, 393, 394, 404, 419, 422, 424, 426, 430, 433, 438, 439, 443, 444, 446, 447, 449, 457, 462, 466, 470, 474, 478, 479, 480, 481, 482, 484, 489, 490, 491, 499, 501, 506, 510, 511, 514, 516, 521, 527, 528, 530, 531, 532, 536, 539, 541, 543], 'yes': [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, ...]}

In [ ]:
mainroad.ngroups

2

In [18]:
mainroad.size()

mainroad
no      77
yes    468
dtype: int64

In [21]:
mainroad.agg({
    'price':['mean','sum'],
    'area':['max','min']
})

                 price               area
                  mean         sum    max   min
mainroad
no        3.398905e+06   261715650   7424  1650
yes       4.991777e+06  2336151790  16200  1700

Q8.  Write  a  python  program  which  display  the  name  and  data  of  the  individual  groups  and
performing groupby on furnishingstatus column of the dataset

In [22]:
data.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus,PricePerSqFt
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished,1792
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished,1367
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished,1229
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished,1628
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished,1537

In [25]:
fs = data.groupby('furnishingstatus')

In [26]:
for name,data in fs:
    print(name)
    print(data)

furnished
        price  area  bedrooms  bathrooms  stories mainroad guestroom basement  \
0    13300000  7420         4          2        3      yes        no       no
1    12250000  8960         4          4        4      yes        no       no
3    12215000  7500         4          2        2      yes        no      yes
4    11410000  7420         4          1        2      yes       yes      yes
8     9870000  8100         4          1        2      yes       yes      yes
..        ...   ...       ...        ...      ...      ...       ...      ...
509   2590000  3600         2          2        2      yes        no      yes
512   2520000  3000         2          1        2      yes        no       no
522   2380000  2475         3          1        2      yes        no       no
523   2380000  2787         4          2        2      yes        no       no
543   1750000  2910         3          1        1       no        no       no

    hotwaterheating airconditioning  parking prefarea furnishingstatus  \
0                no             yes        2      yes        furnished
1                no             yes        3       no        furnished
3                no             yes        3      yes        furnished
4                no             yes        2       no        furnished
8                no             yes        2      yes        furnished
..              ...             ...      ...      ...              ...
509              no              no        1       no        furnished
512              no              no        0       no        furnished
522              no              no        0       no        furnished
523              no              no        0       no        furnished
543              no              no        0       no        furnished

     PricePerSqFt
0            1792
1            1367
3            1628
4            1537
8            1218
..            ...
509           719
512           840
522           961
523           853
543           601

[140 rows x 14 columns]
semi-furnished
        price  area  bedrooms  bathrooms  stories mainroad guestroom basement  \
2    12250000  9960         3          2        2      yes        no      yes
5    10850000  7500         3          3        1      yes        no      yes
6    10150000  8580         4          3        4      yes        no       no
11    9681000  6000         4          3        2      yes       yes      yes
12    9310000  6550         4          2        2      yes        no       no
..        ...   ...       ...        ...      ...      ...       ...      ...
502   2660000  3480         2          1        1      yes        no       no
503   2660000  4000         3          1        1      yes        no       no
514   2485000  3000         3          1        2       no        no       no
527   2275000  1836         2          1        1       no        no      yes
541   1767150  2400         3          1        1       no        no       no

    hotwaterheating airconditioning  parking prefarea furnishingstatus  \
2                no              no        2      yes   semi-furnished
5                no             yes        2      yes   semi-furnished
6                no             yes        2      yes   semi-furnished
11              yes              no        2       no   semi-furnished
12               no             yes        1      yes   semi-furnished
..              ...             ...      ...      ...              ...
502              no              no        1       no   semi-furnished
503              no              no        0       no   semi-furnished
514              no              no        0       no   semi-furnished
527              no              no        0       no   semi-furnished
541              no              no        0       no   semi-furnished

     PricePerSqFt
2            1229
5            1446
6            1182
11           1613
12           1421
..            ...
502           764
503           665
514           828
527          1239
541           736

[227 rows x 14 columns]
unfurnished
        price   area  bedrooms  bathrooms  stories mainroad guestroom  \
7    10150000  16200         5          3        2      yes        no
9     9800000   5750         3          2        4      yes       yes
16    9100000   6600         4          2        2      yes       yes
21    8680000   7155         3          2        1      yes       yes
28    8400000   7950         5          2        2      yes        no
..        ...    ...       ...        ...      ...      ...       ...
538   1890000   3649         2          1        1      yes        no
539   1855000   2990         2          1        1       no        no
540   1820000   3000         2          1        1      yes        no
542   1750000   3620         2          1        1      yes        no
544   1750000   3850         3          1        2      yes        no

    basement hotwaterheating airconditioning  parking prefarea  \
7         no              no              no        0       no
9         no              no             yes        1      yes
16       yes              no             yes        1      yes
21       yes              no             yes        2       no
28       yes             yes              no        2       no
..       ...             ...             ...      ...      ...
538       no              no              no        0       no
539       no              no              no        1       no
540      yes              no              no        2       no
542       no              no              no        0       no
544       no              no              no        0       no

    furnishingstatus  PricePerSqFt
7        unfurnished           626
9        unfurnished          1704
16       unfurnished          1378
21       unfurnished          1213
28       unfurnished          1056
..               ...           ...
538      unfurnished           517
539      unfurnished           620
540      unfurnished           606
542      unfurnished           483
544      unfurnished           454

[178 rows x 14 columns]