In [2]:
import pandas as pd
import numpy as np

In [3]:
data = pd.read_csv('./Data/StudentsPerformance.csv')

In [4]:
data.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [5]:
data.value_counts('race/ethnicity')

race/ethnicity
group C    319
group D    262
group B    190
group E    140
group A     89
Name: count, dtype: int64

In [7]:
data.rename(columns={'race/ethnicity':'groups'},inplace=True)

In [66]:
data.sample(5)

,gender,groups,parental level of education,lunch,test preparation course,math score,reading score,writing score
827,female,group C,some high school,standard,none,65,69,76
486,male,group D,some college,free/reduced,none,61,47,56
119,female,group C,some college,standard,none,55,69,65
636,female,group B,high school,free/reduced,completed,67,80,81
831,female,group C,bachelor's degree,free/reduced,completed,74,86,89